spring.application.name=api
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ywfsmiiawxndnofxltix
spring.datasource.password=Usuario.25.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configuración TheGamesDB
thegamesdb.apiKey=193086162abaed573c5af9be646039a0c2c63fe02164b1139e7f475e7ef53113
thegamesdb.api.base-url=https://api.thegamesdb.net/v1